name: Build A15-6.6

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "Kernel SU Variant"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
          - WKSU
          - MamboSU
        default: WKSU
      kernelsu_branch:
        description: "KSU Branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
        default: Dev
      kernelsu_custom_commit_hash:
        description: "KSU commit hash to apply to kernel. Use latest if you want to get latest commit"
        required: false
        type: string
        default: latest
      use_zram:
        description: 'Add ZRAM'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Enable the KPM feature?'
        required: false
        type: boolean
        default: true
      get_manager:
        description: 'Get the latest KSU Manager? (Experimental feature, please disable if errors occur)'
        required: true
        type: boolean
        default: true
      BBG:
        description: "Enable kernel-level blocking of unauthorized writes to critical partitions/device nodes (LSM)ï¼Ÿ"
        required: true
        type: boolean
        default: false
      nomount_support:
        description: "Enable kernel-level systemless modification (NoMount) compability"
        required: true
        type: boolean
        default: true
      custom_kernel_source:
        description: "Compile kernel from another source instead of rodin source. Use rodin if you want to use rodin src"
        required: false
        type: string
        default: rodin
      custom_susfs_commit_hash:
        description: "Susfs4ksu custom commit hash. Use latest to get latest commit"
        required: false
        type: string
        default: latest
      clang_custom_link:
        description: "Clang link you want to use to compile the kernel"
        required: true
        type: string
        default: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android15-release/clang-r510928.tar.gz
jobs:
 get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
 build-kernel-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      BBG: ${{ inputs.BBG }}
      nomount_support: ${{ inputs.nomount_support }}
      clang_custom_link: ${{ inputs.clang_custom_link }}
      kernelsu_custom_commit_hash: ${{ inputs.kernelsu_custom_commit_hash }}
      custom_kernel_source: ${{ inputs.custom_kernel_source }}
      custom_susfs_commit_hash: ${{ inputs.custom_susfs_commit_hash }}
 
